# Generated by Django 2.2 on 2019-04-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Account',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
